baseURL = "https://sheetanshuprasad.github.io/"
languageCode = "en-us"
title = "Sound Progression"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
description = "Learn Music. Build a Career."
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true

[menu]

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 20

  [[menu.main]]
  identifier = "privacy"
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 30
