baseURL = "https://sheetanshuprasad.github.io/"
languageCode = "en-us"
title = "Sound Progression"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
description = "Learn Music. Build a Career."
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true

defaultTheme = "dark"
disableThemeToggle = true

label = { text = "Sound Progression", icon = "/logoo.png", iconHeight = 35 }

[params.profileMode]
enabled = true
title = "Sound Progression"
subtitle = "Learn Music. Build a Career. Helping producers, mix engineers and mastering engineers build real-world skills and income."

[[params.profileMode.buttons]]
name = "Latest Articles"
url = "/posts/"

[menu]

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

  [[menu.main]]
  identifier = "author"
  name = "Author"
  url = "/about-the-author/"
  weight = 15
  
  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 20

  [[menu.main]]
  identifier = "privacy"
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 30

  [[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 40
